name: Auto Deploy to EC2

on:
  push:
    branches:
      - gaurav  # 👈 Trigger this on push to your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd CTFd || git clone https://github.com/gaurav0973/CTFd.git && cd CTFd
            git checkout gaurav
            git pull origin gaurav
            docker compose down
            docker compose up -d --build
