# This GitHub Actions workflow deploys CTFd to an EC2 instance using SSH and Docker Compose.
name: Deploy CTFd to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd CTFd
            git pull origin main
            docker compose down
            docker compose up -d --build

